---
title: "Python"
output: pdf_document
---

```{r}
library(tidyverse)
```


```{r}
Sys.which("python")
use_condaenv()
conda_list()
Sys.setenv(RETICULATE_PYTHON = '/opt/anaconda3/bin/python3.7')
library(reticulate)
use_python("/opt/anaconda3/bin/python3.7")
py_config()
```


```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import time
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer  
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 

micro = pd.read_csv('microwave.tsv', sep='\t')
hair = pd.read_csv('hair_dryer.tsv', sep='\t')
pacf = pd.read_csv('hair_dryer.tsv', sep='\t')
```

```{python}
hair_cut = pd.read_csv('hair_dryer_line_seperate_words.csv')
ncr = pd.read_csv('nrc.csv')

corpus = hair['review_body'].tolist()
#将文本中的词语转换为词频矩阵  
vectorizer = CountVectorizer()  
#计算个词语出现的次数  
X = vectorizer.fit_transform(corpus)  
#获取词袋中所有文本关键词  
word = vectorizer.get_feature_names()  
transformer = TfidfTransformer()  
print(transformer)
#将词频矩阵X统计成TF-IDF值  
tfidf = transformer.fit_transform(X)  

#建立所有词汇的tf-idf矩阵
tfidf = tfidf.toarray()
tfidf = pd.DataFrame(tfidf, columns=word)
hair_score = hair['star_rating']
ths = pd.concat([hair_score, tfidf], axis=1)

#删除全部为0的列
# n = 0
# a = {0}
# valid_word = []
# for i in word:
#     if set(tfidf[:, n])!=a:
#         valid_word.append(n)
#     n = n + 1

#建立只有情感词汇的tf-idf矩阵，删除横轴为空的向量；
ncr = ncr['word'].tolist()
ncr = [i for i in word if i in ncr]
ncr.append('star_rating')
ths = ths.loc[:, ncr]
dropall = ths.loc[~(ths==0).all(axis=1), :]

#清洗发现每个纵轴都有非零数据
ncr.remove('star_rating')
tfidf_train = np.array(ths.loc[0:8000, ncr])
tfidf_test = np.array(ths.loc[8000:, ncr])
tfidf_score_train = np.array(ths.loc[0:8000, 'star_rating'])
tfidf_score_test = np.array(ths.loc[8000:, 'star_rating'])
```

```{python}
a1 = time.perf_counter()
regress=LinearRegression()
regress.fit(tfidf_train, tfidf_score_train)
a2 = time.perf_counter()
a2-a1
tfidf_score_predict = regress.predict(tfidf_test)
mse = np.power((tfidf_score_predict-tfidf_score_test), 2)

num = 0
for i in range(len(tfidf_score_predict)):
    a = round(tfidf_score_predict[i])
    if (a-tfidf_score_test[i])<=1:#预测相差2星以内均可接受
        num = num + 1
num

coefficient = regress.intercept_
```

```{r}
coefficient = py$coefficient
length(coefficient)

dim(py$tfidf_train)
```

```{r}

predict = py$tfidf_score_predict %>% 
  round()
data.frame(true = py$tfidf_score_test, predict = predict)
```



