---
title: "情感分析"
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: "hyperref,"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(ggplot2)
library(reticulate)
library(tidyverse)
library(tidytext)
library(dplyr)
library(textdata)
library(tidyr)

```

```{r}
hair_dryer = read.csv("hair_dryer.tsv", sep = "\t")
microwave = read.csv("microwave.tsv", sep = "\t")
pacifier = read.csv("pacifier.tsv", sep = "\t")
dat = as.factor(hair_dryer$product_parent) %>% 
  summary()
```

# 情感分析

```{r}
text_df = tibble(line = 1: nrow(pacifier), text = as.character(pacifier$review_body))
tidy_df = text_df %>% 
  unnest_tokens(word, text)
data(stop_words)
tidy_df = tidy_df %>% 
  anti_join(stop_words)

write.csv(tidy_df, "pacifier_line_seperate_words.csv", row.names = FALSE)

dat = tidy_df %>% 
  group_by(line) %>% 
  summarise(n())

write.csv(dat, "hair_dryer_line_n_words.csv", row.names = FALSE)

tidy_df %>% 
  count(word, sort = TRUE)

tidy_df %>%
  count(word, sort = TRUE) %>%
  filter(n > 1000) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```


```{r}
bing_word_counts <- tidy_df %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()
bing_word_counts %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_grid(row = vars(sentiment), scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip()
```







```{r}
nrc = get_sentiments("nrc")
write.csv(nrc, "nrc.csv", row.names = FALSE)


nrc_joy = bing %>% 
  filter(sentiment == "joy")

tidy_df %>%
  inner_join(bing) %>%
  count(sentiment, sort = TRUE) %>% 
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

jane_austen_sentiment <- tidy_books %>%
  inner_join(get_sentiments("bing")) %>%
  count(book, index = linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
```


# BY graph

```{r}
tidy_df = text_df %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2)

austen_bigrams
```












```{r}
bing = read.csv("bing.csv")
bing_positive = bing %>% 
  filter(sentiment == "positive")
text_df = tibble(line = 1: nrow(hair_dryer), text = as.character(hair_dryer$review_body))
tidy_df = text_df %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  inner_join(bing_positive)
tidy_df %>%
  count(word, sort = TRUE) %>%
  mutate(word = reorder(word, n))

bing_negative = bing %>% 
  filter(sentiment == "negative")
text_df = tibble(line = 1: nrow(hair_dryer), text = as.character(hair_dryer$review_body))
tidy_df = text_df %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  inner_join(bing_negative)
tidy_df %>%
  count(word, sort = TRUE) %>%
  mutate(word = reorder(word, n))
```






